export { default as Section } from "./Section.vue"
export { default as SectionHeader } from "./SectionHeader.vue"
export { default as SectionHeading } from "./SectionHeading.vue"
export { default as SectionSubheading } from "./SectionSubheading.vue"
export { default as SectionLink } from "./SectionLink.vue"
